# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 03:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouchStatus',
            fields=[
                ('db_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('db_seq', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PendingDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', django.contrib.postgres.fields.jsonb.JSONField()),
                ('imported', models.DateTimeField(auto_now_add=True)),
                ('process_status', models.CharField(max_length=16, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('table_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('table_timestamp', models.DateTimeField()),
            ],
        ),
    ]
