# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 01:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishCatch',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('weightKgs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FishingEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('numberInTrip', models.IntegerField(blank=True)),
                ('targetSpecies', models.CharField(blank=True, max_length=50)),
                ('datetimeAtStart', models.DateTimeField()),
                ('datetimeAtEnd', models.DateTimeField(blank=True)),
                ('committed', models.BooleanField()),
                ('locationAtStart', django.contrib.postgres.fields.jsonb.JSONField()),
                ('locationAtEnd', django.contrib.postgres.fields.jsonb.JSONField()),
                ('lineString', django.contrib.postgres.fields.jsonb.JSONField()),
                ('eventSpecificDetails', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mitigationDeviceCodes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('vesselNumber', models.IntegerField()),
                ('isVesselUsed', models.BooleanField()),
                ('completed', models.DateTimeField()),
                ('eventVersion', models.DateTimeField()),
                ('notes', models.TextField()),
                ('completedDateTime', models.DateTimeField()),
                ('amendmentReason', models.TextField()),
                ('archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FishReciever',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NonFishProtectedSpeciesInteractionEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('seabirdCaptureCode', models.CharField(max_length=3)),
                ('estimatedWeightKg', models.DecimalField(decimal_places=4, max_digits=12)),
                ('numberUninjured', models.IntegerField(blank=True)),
                ('numberInjured', models.IntegerField(blank=True)),
                ('numberDead', models.IntegerField(blank=True)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField()),
                ('eventHeader', django.contrib.postgres.fields.jsonb.JSONField()),
                ('isVesselUsed', models.BooleanField()),
                ('completed', models.DateTimeField()),
                ('eventVersion', models.DateTimeField()),
                ('notes', models.TextField()),
                ('completedDateTime', models.DateTimeField()),
                ('amendmentReason', models.TextField()),
                ('archived', models.BooleanField()),
                ('fishingEvent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.FishingEvent')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedState',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3)),
                ('fullName', models.CharField(max_length=50)),
                ('conversionFactor', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('speciesType', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('otherNames', models.TextField(blank=True, max_length=50)),
                ('fullName', models.CharField(blank=True, max_length=50)),
                ('scientificName', models.CharField(blank=True, max_length=50)),
                ('image', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('personInCharge', models.CharField(max_length=50)),
                ('ETA', models.DateTimeField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('startLocation', django.contrib.postgres.fields.jsonb.JSONField()),
                ('endLocation', django.contrib.postgres.fields.jsonb.JSONField()),
                ('unloadPort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Port')),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('registration', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Vessel'),
        ),
        migrations.AddField(
            model_name='processedstate',
            name='Species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Species'),
        ),
        migrations.AddField(
            model_name='nonfishprotectedspeciesinteractionevent',
            name='nonFishProtectedSpecies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Species'),
        ),
        migrations.AddField(
            model_name='nonfishprotectedspeciesinteractionevent',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Trip'),
        ),
        migrations.AddField(
            model_name='fishingevent',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Trip'),
        ),
        migrations.AddField(
            model_name='fishcatch',
            name='fishingEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishCatches', to='reporting.FishingEvent'),
        ),
        migrations.AddField(
            model_name='fishcatch',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Species'),
        ),
    ]
