# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingevent',
            name='datetimeAtEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='datetimeAtStart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='numberInTrip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='targetSpecies',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
