# Generated by Django 2.0.dev20170831062519 on 2017-09-01 04:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Vessel')),
            ],
        ),
        migrations.AlterField(
            model_name='fishcatch',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.Species'),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='RAId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='datetimeAtEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='lineString',
            field=django.contrib.gis.db.models.fields.LineStringField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='locationAtEnd',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='locationAtStart',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='numberInTrip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='targetSpecies',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nonfishingevent',
            name='nonFishProtectedSpecies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.Species'),
        ),
        migrations.AlterField(
            model_name='nonfishingevent',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Trip'),
        ),
        migrations.AlterField(
            model_name='port',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='processedstate',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.Species'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='RAId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='endLocation',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startLocation',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='unloadPort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.Port'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.Vessel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddIndex(
            model_name='vessellocation',
            index=models.Index(fields=['vessel', 'timestamp'], name='reporting_v_vessel__f03e42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vessellocation',
            unique_together={('vessel', 'timestamp')},
        ),
    ]
