# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20170824_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FishReciever',
        ),
        migrations.AddField(
            model_name='trip',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Organisation'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Organisation'),
        ),
    ]
