# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20170901_0451'),
        ('reporting', '0002_auto_20170904_2344'),
    ]

    operations = [
    ]
