# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 23:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20170818_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingevent',
            name='amendmentReason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='committed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='isVesselUsed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='lineString',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='mitigationDeviceCodes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
