# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 02:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20170906_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='id',
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='species',
            name='code',
            field=models.CharField(editable=False, max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='reporting.Vessel'),
        ),
    ]
