# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20170908_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishcatch',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Species'),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='targetSpecies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Species'),
        ),
        migrations.AlterField(
            model_name='nonfishingevent',
            name='nonFishProtectedSpecies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Species'),
        ),
        migrations.AlterField(
            model_name='processedstate',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Species'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='unloadPort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Port'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='reporting.Vessel'),
        ),
    ]
