# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_remove_fishingevent_eventversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingevent',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
