# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20170821_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingevent',
            name='RAId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='RAId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
