# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20170913_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishServeEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(null=True)),
                ('response', models.TextField(null=True)),
            ],
        ),
    ]
