# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_fishserveevents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FishServeEvents',
        ),
    ]
