# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_delete_fishserveevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='extra_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
