# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20170918_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('landedState', models.CharField(max_length=3)),
                ('containers', models.IntegerField(null=True)),
                ('containerType', models.CharField(max_length=3, null=True)),
                ('contentWeight', models.IntegerField(null=True)),
                ('destinationType', models.CharField(max_length=1)),
                ('destinationNumber', models.CharField(max_length=32, null=True)),
                ('greenWeight', models.IntegerField()),
                ('invoiceNumber', models.CharField(max_length=32, null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Species')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Trip')),
            ],
        ),
        migrations.RemoveField(
            model_name='nonfishingevent',
            name='amendmentReason',
        ),
        migrations.RemoveField(
            model_name='nonfishingevent',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='nonfishingevent',
            name='eventHeader',
        ),
        migrations.RemoveField(
            model_name='nonfishingevent',
            name='eventVersion',
        ),
        migrations.AlterField(
            model_name='nonfishingevent',
            name='estimatedWeightKg',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='nonfishingevent',
            name='tags',
        ),
        migrations.AddField(
            model_name='nonfishingevent',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=None),
        ),
    ]
