# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_auto_20171002_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='landingevent',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landingEvents', to='reporting.Trip'),
        ),
    ]
