# Generated by Django 2.0.1 on 2018-01-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_auto_20171010_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingevent',
            name='sentToShop',
            field=models.BooleanField(default=False),
        ),
    ]
