# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-07 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_auto_20180529_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingevent',
            name='vesselNumber',
            field=models.IntegerField(null=True),
        ),
    ]
