# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-07 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0017_auto_20180707_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishcatch',
            name='fishingEvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fishCatches', to='reporting.FishingEvent'),
        ),
    ]
