# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishserveevents',
            name='event_id',
            field=models.UUIDField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishserveevents',
            name='event_type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
