# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fishserve', '0002_auto_20170918_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishserveevents',
            name='event_id',
        ),
        migrations.AddField(
            model_name='fishserveevents',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
