# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishserve', '0003_auto_20170918_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishserveevents',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
